# Dockerfile.dev
FROM node:20-alpine
 
WORKDIR /app
 
# First copy only package files for caching
COPY package*.json package-lock.json ./
 
# Install dependencies (include --legacy-peer-deps if needed)
RUN npm install --legacy-peer-deps
 
# Then copy the rest of the files
COPY . .
 
# Build the Angular app (if needed)
RUN npm run build
 
CMD ["npm", "start"]