name: Build and Deploy Frontend

on:
  workflow_dispatch:

jobs:
  build_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Authenticate with GCP
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set up gcloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      - name: Authenticate Docker with GCP
        run: |
          gcloud auth configure-docker us-central1-docker.pkg.dev

      - name: Build and Push Docker Image for Frontend
        run: |
          docker build -f Dockerfile -t us-central1-docker.pkg.dev/proyecto-final-451719/proyecto/frontend-ccp-image:latest .
          docker push us-central1-docker.pkg.dev/proyecto-final-451719/proyecto/frontend-ccp-image:latest

      - name: Deploy to Cloud Run for Frontend
        run: |
          gcloud run deploy frontend-ccp \
            --image=us-central1-docker.pkg.dev/proyecto-final-451719/proyecto/frontend-ccp-image:latest \
            --region=us-central1 \
            --platform=managed \
            --allow-unauthenticated \
            --memory=512Mi \
            --cpu=1 \
            --concurrency=80 \
            --port=80 \
            --vpc-egress=private-ranges-only \
            --min-instances=1 \
            --max-instances=3
