name: Run Unit Tests with Coverage

on:
  push:
    branches:
      - feature/*

jobs:
  test:
    runs-on: ubuntu-latest
    container: cypress/browsers:node18.12.1-chrome107-ff106

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'

      - name: Install dependencies
        run: |
          npm install
          npm update --depth 20
          npm audit fix --force

      - name: Verify Chrome installation
        run: google-chrome --version

      - name: Run unit tests with coverage
        run: |
          export DISPLAY=:99
          Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
          npm test -- --code-coverage --browsers=ChromeHeadlessCI

      - name: Upload coverage report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: coverage/